version: "3"

services:
  web:
    restart: always
    depends_on:
      - redis
    build: ./server
    networks:
      - shortlinks
    ports:
      - 80:3000
    environment:
      APPLICATION_URL: ${APPLICATION_URL}
      REDIS_URL: ${REDIS_URL}
  redis:
    restart: always
    image: redis:alpine
    networks:
      - shortlinks


networks:
  shortlinks:
